# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: npm/package-name
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
  - https://cardano.org

